fix: stream error will throw the entire exception and not just the er…
supabase-community/supabase-dart pull request #145
Opened 2022-09-25 15:02 UTC by dshukertjr

Previously, errors within `stream()` had String type, which I don't remember why I did it like that. This PR allows the full exception object to be passed through.

2022-09-25 15:07 UTC, Vinzent03 requested changes

2022-09-25 15:07 UTC, Vinzent03 commented on lib/src/supabase_stream_builder.dart
> +      _addException(error);
May we add the stack trace as well?

2022-09-25 15:07 UTC, Vinzent03 commented on lib/src/supabase_stream_builder.dart
> +        _addException(Exception('Could not find the deleted record.'));
Is it possible to add stack trace here as we. May use `StackTrace.current`

2022-09-26 03:41 UTC, dshukertjr commented on lib/src/supabase_stream_builder.dart
> +        _addException(Exception('Could not find the deleted record.'));
Great idea! Added it just now!

2022-09-26 06:59 UTC, Vinzent03 approved these changes

2022-09-27 06:31 UTC, merged