chore: publish v1.0.0 🚀
supabase-community/supabase-dart pull request #152
Opened 2022-10-18 15:09 UTC by dshukertjr

Also included the primary key breaking change discussed [here](https://github.com/supabase-community/supabase-flutter/issues/218#issuecomment-1279038003).

```dart
// Old
supabase.from('table').stream(['id']);

// New
supabase.from('table').stream(primaryKey: ['id']);
```

2022-10-18 17:20 UTC, Vinzent03 requested changes

2022-10-18 17:20 UTC, Vinzent03 commented on lib/src/supabase_query_builder.dart
> +    assert(primaryKey.isNotEmpty, 'Please specify parimary key(s).');
We should change the name and typo here.

2022-10-19 02:24 UTC, dshukertjr commented on lib/src/supabase_query_builder.dart
> +    assert(primaryKey.isNotEmpty, 'Please specify parimary key(s).');
Thanks for picking up on the typo! What are you suggesting about the name change?

2022-10-19 06:57 UTC, Vinzent03 commented on lib/src/supabase_query_builder.dart
> +    assert(primaryKey.isNotEmpty, 'Please specify parimary key(s).');
There is again the plural of primary key. I would remove ` (s)`

2022-10-19 07:03 UTC, dshukertjr commented on lib/src/supabase_query_builder.dart
> +    assert(primaryKey.isNotEmpty, 'Please specify parimary key(s).');
@Vinzent03 Sure, how about right now?

2022-10-19 07:14 UTC, Vinzent03 approved these changes
LGTM!

2022-10-19 07:20 UTC, dshukertjr commented
Thanks for the quick review! Exciting times! Now I will work on the supabase-flutter rework, and we can finally release v1!

2022-10-19 07:20 UTC, merged